### ISSUE TITLE
Cassini ISS Users Guide returns "No Document Information found in the registry" msg

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS/registry-legacy-solr#163]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I noticed when entering the DOI for the Cassini ISS Users Guide (10.17189/1504135), it results in a "No Document Information found in the registry" message. 

<img width="1511" alt="Screenshot 2024-11-08 at 14 44 45" src="https://github.com/user-attachments/assets/ab0e786f-522c-4354-a4aa-9c94e6476f93">

(This label lists the DOI: https://pds-rings.seti.org/pds4/bundles/cassini_iss_saturn/document/iss-data-user-guide.xml.)

### 🕵️ Expected behavior

I expected the Cassini ISS Users Guide to be found.

### 📜 To Reproduce

doi.org/10.17189/1504135

https://pds.nasa.gov/ds-view/pds/viewDocument.jsp?identifier=urn%3Anasa%3Apds%3Acassini_iss_saturn%3Adocument%3Aiss-data-user-guide&version=1.0

**Comment by jordanpadams** [comment]
For some reason, this data was not loaded when all the other data products were loaded. This should now be fixed.

**Comment by mace-space** [comment]
Thanks for looking into this @jordanpadams. I'm still seeing the "No Document Information found in the registry" message

**Comment by mace-space** [comment]
Looks to be fixed now, thanks

**Comment by jordanpadams** [comment]
+1 great. thanks @mace-space
